print()
print("\033[31mA simple Python input and output script\033[0m")
print()
name = input("\033[32mWhat is your name?\033[0m ")
print()
print("Hi", name, ", nice to meet you!")
print()
favFood = input("\033[33mWhat is your favorite food?\033[0m ")
print()
print("Wow! me too. I love", favFood)
print()
favSport = input("\033[34mWhat is your favorite sport?\033[0m ")
print()
print("Unfortunately, I don't like", favSport)
print()
print("\033[31mThank you", name,
      "for trying my day 2 Python code. Follow me on Twitter, Replit, or here on YouTube.\033[0m")
print()
