print("A simple python input/output code")
print()
myName = input("What's your name?: ")
print("Thanks " + myName + " for trying my code")
print()
favFood = input("What's your favorite food?: ")
print("Wow, me too. I love " + favFood)
print()
favSport = input("Okay, what's your favorite sport?: ")
print("Wait!, " + favSport + " is my favorite sport too.")
print()
print("We are two for two.")
favVacation = input("Hey " + myName + ", what's your favorite vacation spot? ")
print("Please don't tell me it's " + favVacation + ".")
print("No way, it's like I know what you're going to type.")
print()
print("I hope you had fun using my code." +
      " It was a pleasure meeting you, have a great day " + myName + ".")
