print("Welcome to your adventure simulator. I am going to ask you a few questions and then create an epic story with you as the star!")
print()
myName = input("What's your name? ")
print("Hi,", myName, "it's a pleasure to meet you.")
print()
bestFriend = input("What's your best friend’s name? ")
print(bestFriend, "\033[0m" ",that's a lovely name")
print()
print("This is a good start, just a few more questions.")
print()
favTech = input("What's your favorite device? ")
print("That's also my favorite device")
print()
favTreat = input("What are your favorite candies? ")
print(favTreat, "?, don't eat too many of those.")
print()
vacation = input("Where would you like to live? ")
print("I vacationed there once, it's lovely during spring.")

print()
food = input("What's your favorite food? ")
print("Oh no, first", favTreat, ",and now",
      food, ",we need a new diet plan.")
print()
feeling = input("Give me another word for joyful? ")
print("\033[36m", feeling, "\033[0m"", That's a nice word.")
print()
print("Okay, let's see what", "\033[31m",
      "adventure", "\033[0m", "we simulated.")
print()
input("Press the return/enter key to simulate yoru adventure.")
print()
print("Hi, my name is ""\033[35m", myName, "\033[0m"" and I need help. My best friend,""\033[33m", bestFriend, "\033[0m"" is addicted to, let's call them, illegal ""\033[34m", favTreat, "\033[0m"". These ""\033[34m", favTreat, "\033[0m"" make my bestfriend " "\033[36m", feeling, "\033[0m"" ,but they also have a dark side. They cause", bestFriend, "to turn into a""\033[31m", favTech, " after midnight.""\033[0m" " Causes""\033[33m", bestFriend,
      "\033[0m"" to go around town eating all the""\033[32m", food, "\033[0m"" in the city, and the next day, we are all out of""\033[32m", food, "\033[0m"". But", bestFriend, "is unwilling to give up the,""\033[34m", favTreat, "\033[0m" "so I will become a""\033[31m", favTech, "\033[0m"" with", bestFriend, " and eat the ""\033[32m", food, "\033[0m"" too. After that, ""\033[31m", vacation, "\033[0m"" will never be the same again.")
print()
