print("================================")
print("**     GENERATION GENERATOR   **")
print("================================")
print()
name = input("What is your name?. ")
print()
print("Hi", name)
print()
print("Hi", name, "I'm  a generation generator. I will tell you what generation you belong to.")
print()
year = int(input("What year were you born?. "))
print()
if (year <= 1945 and year >= 1925):
    print("You belong to the Traditionalist Generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
elif (year <= 1964 and year >= 1946):
    print("You belong to the Baby Boomer Generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
elif (year <= 1980 and year >= 1965):
    print("You belong to the Generation X Generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
elif (year <= 1996 and year >= 1981):
    print("You belong to the Millennial Generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
elif (year <= 2012 and year >= 1997):
    print("You belong to the Generation Z Generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
elif (year <= 2020 and year >= 2013):
    print("You belong to the Generation Alpha Generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
else:
    print("You are not part of any generation.")
    print()
    print("Thank you", name, "for trying my generation generator.")
    print()
print("================================")
print("**     GENERATION GENERATOR   **")
print("================================")
print()
print("Generation information provided by www.generationresearch.com.")
print()
